# Generated by Django 4.0 on 2021-12-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_produto_cep_produto_endereco_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
